table dataset
	lineageTag: ec44d896-da2f-4d02-8f1a-108131017ba8

	column ID_Pedido
		dataType: string
		lineageTag: da27adc9-120c-4b74-96a9-acf9c896971b
		summarizeBy: none
		sourceColumn: ID_Pedido

		annotation SummarizationSetBy = Automatic

	column Data_Pedido
		dataType: dateTime
		formatString: Long Date
		lineageTag: b9970e32-fa1e-48a8-ac12-c1071f87a8d9
		summarizeBy: none
		sourceColumn: Data_Pedido

		variation Variation
			isDefault
			relationship: 60e031e5-4017-4164-86ce-d5bd9ce14db4
			defaultHierarchy: LocalDateTable_765f3a07-924f-468d-8992-7a5716dff9f7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ID_Cliente
		dataType: string
		lineageTag: 4fa4dfac-c2cc-4a66-badc-cf5f943ea5bd
		summarizeBy: none
		sourceColumn: ID_Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: 6f260dc2-fd73-4a37-9964-af55ed64eb47
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Regiao
		dataType: string
		lineageTag: a1b7f686-ba1f-4d68-bc05-7b65d21376d2
		summarizeBy: none
		sourceColumn: Regiao

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: 20d2327a-7c85-44f6-ade1-6cca4b410bca
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: cfb7c3f3-5639-4b4a-a956-6d93281a61c3
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: eb7d964d-98f0-4b2c-9d61-918c717b9a12
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column SubCategoria
		dataType: string
		lineageTag: aab2785d-daf4-4778-bf7f-6141d660774a
		summarizeBy: none
		sourceColumn: SubCategoria

		annotation SummarizationSetBy = Automatic

	column Total_Vendas
		dataType: double
		lineageTag: ae65c89d-64ec-46ef-9a95-6b4377383eff
		summarizeBy: sum
		sourceColumn: Total_Vendas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantidade
		dataType: int64
		formatString: 0
		lineageTag: 108667d0-2936-473a-9845-09056302b5ba
		summarizeBy: sum
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	column Desconto
		dataType: double
		lineageTag: f7017bd3-74e1-49aa-b47d-385ba63d5a88
		summarizeBy: sum
		sourceColumn: Desconto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lucro
		dataType: double
		lineageTag: 0f7488ae-a71a-411f-a460-df2b37f5310d
		summarizeBy: sum
		sourceColumn: Lucro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prioridade
		dataType: string
		lineageTag: 54a86c70-6415-444b-9b99-1f191c6c88d4
		summarizeBy: none
		sourceColumn: Prioridade

		annotation SummarizationSetBy = Automatic

	partition dataset = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\deeh_\OneDrive\Desktop\dataset.csv"),[Delimiter=";", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID_Pedido", type text}, {"Data_Pedido", type date}, {"ID_Cliente", type text}, {"Segmento", type text}, {"Regiao", type text}, {"Pais", type text}, {"Product ID", type text}, {"Categoria", type text}, {"SubCategoria", type text}, {"Total_Vendas", type number}, {"Quantidade", Int64.Type}, {"Desconto", type number}, {"Lucro", type number}, {"Prioridade", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

